package calc;


/**
* CalculatricePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* Wednesday, November 16, 2016 2:40:19 PM WAT
*/

public abstract class CalculatricePOA extends org.omg.PortableServer.Servant
 implements CalculatriceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ajouter", new java.lang.Integer (0));
    _methods.put ("soustraire", new java.lang.Integer (1));
    _methods.put ("multiplier", new java.lang.Integer (2));
    _methods.put ("memoriser_dernier_resultat", new java.lang.Integer (3));
    _methods.put ("extraire_memoire", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Calculatrice/ajouter
       {
         float a1 = in.read_float ();
         float a2 = in.read_float ();
         float $result = (float)0;
         $result = this.ajouter (a1, a2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // Calculatrice/soustraire
       {
         float a1 = in.read_float ();
         float a2 = in.read_float ();
         float $result = (float)0;
         $result = this.soustraire (a1, a2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // Calculatrice/multiplier
       {
         float a1 = in.read_float ();
         float a2 = in.read_float ();
         float $result = (float)0;
         $result = this.multiplier (a1, a2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // Calculatrice/memoriser_dernier_resultat
       {
         this.memoriser_dernier_resultat ();
         out = $rh.createReply();
         break;
       }

       case 4:  // Calculatrice/extraire_memoire
       {
         org.omg.CORBA.FloatHolder registre = new org.omg.CORBA.FloatHolder ();
         registre.value = in.read_float ();
         float $result = (float)0;
         $result = this.extraire_memoire (registre);
         out = $rh.createReply();
         out.write_float ($result);
         out.write_float (registre.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Calculatrice:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Calculatrice _this() 
  {
    return CalculatriceHelper.narrow(
    super._this_object());
  }

  public Calculatrice _this(org.omg.CORBA.ORB orb) 
  {
    return CalculatriceHelper.narrow(
    super._this_object(orb));
  }


} // class CalculatricePOA
