package calc;


/**
* CalculatriceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* Wednesday, November 16, 2016 2:40:19 PM WAT
*/

public interface CalculatriceOperations 
{
  float ajouter (float a1, float a2);
  float soustraire (float a1, float a2);
  float multiplier (float a1, float a2);
  void memoriser_dernier_resultat ();
  float extraire_memoire (org.omg.CORBA.FloatHolder registre);
} // interface CalculatriceOperations
