package horlogeClient;


/**
* HorlogePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* Wednesday, November 16, 2016 2:00:16 PM WAT
*/

public abstract class HorlogePOA extends org.omg.PortableServer.Servant
 implements HorlogeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("get_time", new java.lang.Integer (0));
    _methods.put ("get_time_string", new java.lang.Integer (1));
    _methods.put ("get_time_int", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Horloge/get_time
       {
         String $result = null;
         $result = this.get_time ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Horloge/get_time_string
       {
         String $result = null;
         $result = this.get_time_string ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // Horloge/get_time_int
       {
         org.omg.CORBA.ShortHolder heure = new org.omg.CORBA.ShortHolder ();
         org.omg.CORBA.ShortHolder min = new org.omg.CORBA.ShortHolder ();
         this.get_time_int (heure, min);
         out = $rh.createReply();
         out.write_short (heure.value);
         out.write_short (min.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Horloge:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Horloge _this() 
  {
    return HorlogeHelper.narrow(
    super._this_object());
  }

  public Horloge _this(org.omg.CORBA.ORB orb) 
  {
    return HorlogeHelper.narrow(
    super._this_object(orb));
  }


} // class HorlogePOA
