package horlogeClient;


/**
* Horloge.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* Wednesday, November 16, 2016 2:00:17 PM WAT
*/

public interface Horloge extends HorlogeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Horloge
