package calc;

/**
* CalculatriceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* Tuesday, November 22, 2016 9:08:57 AM WAT
*/

public interface CalculatriceOperations 
{
  float ajout (float x, float y);
  float soustrait (float x, float y);
  float mult (float x, float y);
  float divis (float x, float y) throws DivisionParZero;
} // interface CalculatriceOperations
