package banque;


/**
* CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* Tuesday, November 22, 2016 9:51:13 AM WAT
*/

public interface CompteOperations 
{
  boolean deposer (double montant);
  boolean retirer (double montant);
  double afficher ();
} // interface CompteOperations
