package banque;


/**
* Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* Tuesday, November 22, 2016 9:51:13 AM WAT
*/

public interface Compte extends CompteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Compte
