package banque;


/**
* CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* Wednesday, November 23, 2016 4:08:01 PM WAT
*/

public interface CompteOperations 
{
  void deposer (float montant);

  // deposer de l argent
  float Labalance ();

  // get the balance of money
  int getNumcompte ();

  //recuperer le numero de compte
  void retirer (float montant);
} // interface CompteOperations
