package banque;

/**
* Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* Wednesday, November 23, 2016 4:08:01 PM WAT
*/

public interface Compte extends CompteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Compte
