package banque;
import org.omg.CORBA.IntHolder;


/**
* _BankStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Wednesday, November 23, 2016 4:02:09 PM WAT
*/

public class _BankStub extends org.omg.CORBA.portable.ObjectImpl implements Bank
{
 // deplacer vers un compte qui se trouve ds la banque target
@Override
  public Compte chercher (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("chercher", true);
                $out.write_long (id);
                $in = _invoke ($out);
                Compte $result = CompteHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return chercher (id        );
            } finally {
                _releaseReply ($in);
            }
  } // chercher



  

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Bank:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }


@Override
public Compte deplacer(Bank target, Compte a) {
    org.omg.CORBA.portable.InputStream $in = null;
    try {
        org.omg.CORBA.portable.OutputStream $out = _request ("deplacer", true);
        BankHelper.write ($out, target);
        CompteHelper.write ($out, a);
        $in = _invoke ($out);
        Compte $result = CompteHelper.read ($in);
        return $result;
    } catch (org.omg.CORBA.portable.ApplicationException $ex) {
        $in = $ex.getInputStream ();
        String _id = $ex.getId ();
        throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException $rm) {
        return deplacer (target, a        );
    } finally {
        _releaseReply ($in);
    }
} // deplacer


@Override
public void supprimer(Compte a) 
	{
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request ("supprimer", true);
            CompteHelper.write ($out, a);
            $in = _invoke ($out);
            return;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream ();
            String _id = $ex.getId ();
            throw new org.omg.CORBA.MARSHAL (_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            supprimer (a        );
        } finally {
            _releaseReply ($in);
        
} // supprimer
	
}




@Override
public Compte creer(int id) {
    org.omg.CORBA.portable.InputStream $in = null;
    try {
        org.omg.CORBA.portable.OutputStream $out = _request ("creer", true);
        $in = _invoke ($out);
        Compte $result = CompteHelper.read ($in);
        id = $in.read_long ();
        return $result;
    } catch (org.omg.CORBA.portable.ApplicationException $ex) {
        $in = $ex.getInputStream ();
        String _id = $ex.getId ();
        throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException $rm) {
        return creer (id        );
    } finally {
        _releaseReply ($in);
    }
} // creer










} // class _BankStub
