package banque;


/**
* Bank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Wednesday, November 23, 2016 4:02:09 PM WAT
*/

public interface Bank extends BankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

} // interface Bank
