package banque;


/**
* BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Wednesday, November 23, 2016 4:02:09 PM WAT
*/

public interface BankOperations 
{
  banque.Compte creer (int id);

  // creation d un compte
  banque.Compte deplacer (Bank target, Compte a);

  // deplacer vers un compte qui se trouve ds la banque target
  banque.Compte chercher (int id);

  //chercher un compte apres avoir fourni un id
  void supprimer (Compte a);
} // interface BankOperations
