package calc;


/**
* Calculatrice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* Tuesday, November 22, 2016 9:09:11 AM WAT
*/

public interface Calculatrice extends CalculatriceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculatrice
