package calc;

/**
* DivisionParZeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* Tuesday, November 22, 2016 9:09:11 AM WAT
*/

public final class DivisionParZeroHolder implements org.omg.CORBA.portable.Streamable
{
  public DivisionParZero value = null;

  public DivisionParZeroHolder ()
  {
  }

  public DivisionParZeroHolder (DivisionParZero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DivisionParZeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DivisionParZeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DivisionParZeroHelper.type ();
  }

}
